version: '2'
services:
  newfinanceiro-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/NewFinanceiro/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=NewFinanceiro
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
